name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    name: Prepare and publish release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: Get version from tag
        id: version
        run: echo "version=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"

      - name: Set version in manifest.json
        run: |
          sed -i '/version/c\  "version": "${{ steps.version.outputs.version }}"' \
            ${{ github.workspace }}/custom_components/national_grid/manifest.json

      - name: ZIP integration directory
        run: |
          cd ${{ github.workspace }}/custom_components/national_grid
          zip -r national_grid.zip ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/national_grid/national_grid.zip
          asset_name: national_grid.zip
          tag: ${{ github.ref }}
          overwrite: true
