name: Validate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  hassfest: # https://developers.home-assistant.io/blog/2020/04/16/hassfest
    name: Hassfest validation
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run hassfest validation
        uses: home-assistant/actions/hassfest@master

  hacs: # https://github.com/hacs/action
    name: HACS validation
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: Run HACS validation
        uses: hacs/action@main
        with:
          category: integration
          # Remove this 'ignore' key when brand images have been submitted to
          # https://github.com/home-assistant/brands
          ignore: brands
